# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/688eab6d-0e73-46ce-9d25-ce58395d6dc5";
      fsType = "btrfs";
      options = [ "subvol=subvol/root" ];
    };

  boot.initrd.luks.devices."system".device = "/dev/disk/by-uuid/ca5de9e4-7c1e-4805-aa80-96d59f54be5e";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/688eab6d-0e73-46ce-9d25-ce58395d6dc5";
      fsType = "btrfs";
      options = [ "subvol=subvol/home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/688eab6d-0e73-46ce-9d25-ce58395d6dc5";
      fsType = "btrfs";
      options = [ "subvol=subvol/nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/nvme0n1p1";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 8;
  #powerManagement.cpuFreqGovernor = "performance";
}
